import os, json, io, zipfile, datetime
import joblib
import numpy as np
from flask import current_app


def _get_model_dir(dataset_id):
    from services.forecasting_service import _get_forecast_dir
    forecast_dir = _get_forecast_dir(dataset_id)
    return os.path.join(forecast_dir, 'trained_model')


def _detect_framework(model_obj):
    type_str = str(type(model_obj)).lower()
    if 'xgboost' in type_str:
        return 'xgboost'
    if 'lightgbm' in type_str or 'lgbm' in type_str:
        return 'lightgbm'
    if 'catboost' in type_str:
        return 'catboost'
    if 'keras' in type_str or 'tensorflow' in type_str:
        return 'tensorflow'
    if 'statsmodels' in type_str or 'arima' in type_str or 'sarimax' in type_str or 'exponentialsmoothing' in type_str:
        return 'statsmodels'
    if 'sklearn' in type_str or 'linearregression' in type_str or 'randomforest' in type_str:
        return 'sklearn'
    if 'prophet' in type_str:
        return 'prophet'
    return 'unknown'


def _get_framework_versions():
    versions = {}
    try:
        import sklearn
        versions['scikit-learn'] = sklearn.__version__
    except Exception:
        pass
    try:
        import xgboost
        versions['xgboost'] = xgboost.__version__
    except Exception:
        pass
    try:
        import lightgbm
        versions['lightgbm'] = lightgbm.__version__
    except Exception:
        pass
    try:
        import catboost
        versions['catboost'] = catboost.__version__
    except Exception:
        pass
    try:
        os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
        os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
        import tensorflow as tf
        versions['tensorflow'] = tf.__version__
    except Exception:
        pass
    try:
        import statsmodels
        versions['statsmodels'] = statsmodels.__version__
    except Exception:
        pass
    try:
        import prophet
        versions['prophet'] = prophet.__version__
    except Exception:
        pass
    try:
        import numpy as np
        versions['numpy'] = np.__version__
    except Exception:
        pass
    try:
        import pandas as pd
        versions['pandas'] = pd.__version__
    except Exception:
        pass
    try:
        import joblib
        versions['joblib'] = joblib.__version__
    except Exception:
        pass
    return versions


def _generate_requirements(framework):
    reqs = [
        'numpy>=1.21.0',
        'pandas>=1.3.0',
        'joblib>=1.1.0',
        'scikit-learn>=1.0.0',
    ]
    if framework == 'xgboost':
        reqs.append('xgboost>=1.5.0')
    elif framework == 'lightgbm':
        reqs.append('lightgbm>=3.3.0')
    elif framework == 'catboost':
        reqs.append('catboost>=1.0.0')
    elif framework == 'tensorflow':
        reqs.append('tensorflow>=2.8.0')
    elif framework == 'statsmodels' or framework in ('arima', 'sarima', 'exponentialsmoothing'):
        reqs.append('statsmodels>=0.13.0')
    elif framework == 'prophet':
        reqs.append('prophet>=1.1.0')
    return '\n'.join(reqs)


def _generate_readme(metadata):
    model_name = metadata.get('forecast_model', 'Model')
    target_col = metadata.get('target_column', 'target')
    date_col = metadata.get('date_column', 'date')
    feature_cols = metadata.get('feature_columns', [])
    framework = metadata.get('framework', 'sklearn')

    readme = f"""========================================
{model_name} - Trained Forecast Model
========================================
Generated by ForecastIQ Universal Forecasting Platform

This package contains a trained forecasting model ready for use.

========================================
FILES INCLUDED
========================================
model.pkl              - Trained forecasting model (joblib format)
preprocessor.pkl       - Preprocessing pipeline (feature engineering config)
feature_columns.json   - Feature column names in the exact training order
metadata.json          - Model metadata and training configuration
README.txt             - This file
requirements.txt       - Python dependencies

========================================
MODEL INFORMATION
========================================
Model: {model_name}
Target Column: {target_col}
Date Column: {date_col}
Feature Count: {len(feature_cols)}
Framework: {framework}
Training Timestamp: {metadata.get('training_timestamp', 'Unknown')}
Training Samples: {metadata.get('training_samples', 'N/A')}
Testing Samples: {metadata.get('testing_samples', 'N/A')}

========================================
HOW TO LOAD THE MODEL
========================================
Python script to load the trained model:

    import joblib
    import json

    # Load the trained model
    model = joblib.load('model.pkl')

    # Load the preprocessor
    preprocessor = joblib.load('preprocessor.pkl')

    # Load feature columns
    with open('feature_columns.json', 'r') as f:
        feature_columns = json.load(f)

    # Load metadata
    with open('metadata.json', 'r') as f:
        metadata = json.load(f)

    print(f"Loaded {metadata['forecast_model']} model")
    print(f"Features: {{feature_columns}}")

========================================
HOW TO MAKE PREDICTIONS
========================================
Example with pandas DataFrame:

    import pandas as pd
    import joblib
    import json

    model = joblib.load('model.pkl')
    preprocessor = joblib.load('preprocessor.pkl')

    # Load your new data as a DataFrame
    # The DataFrame must have the same columns used during training
    # df = pd.read_csv('new_data.csv')

    # Feature columns in exact training order
    with open('feature_columns.json', 'r') as f:
        feature_columns = json.load(f)

    # Prepare features
    # X = df[feature_columns].fillna(0)

    # Make predictions
    # predictions = model.predict(X)
    # print(predictions)

========================================
SAMPLE PREDICTION SCRIPT
========================================
A complete working example:

    import joblib
    import json
    import numpy as np

    # Load model and metadata
    model = joblib.load('model.pkl')
    with open('metadata.json', 'r') as f:
        metadata = json.load(f)

    # Create sample input with correct number of features
    n_features = len(metadata.get('feature_columns', []))
    if n_features > 0:
        sample = np.random.rand(1, n_features)
        prediction = model.predict(sample)
        print(f"Sample prediction: {{prediction}}")
    else:
        print("Time-series model: predictions are made sequentially")

Note: For time-series models (ARIMA, SARIMA, ETS, LSTM), predictions
are generated sequentially rather than from feature inputs.
Use the model object's native predict/forecast method.

========================================
LICENSE
========================================
This model was trained using ForecastIQ. Usage is subject to
the terms under which the original dataset was provided.
"""
    return readme


def _trim_statsmodels_model(model_obj):
    _MAX_OBS = 100

    if hasattr(model_obj, 'filter_results'):
        fr = model_obj.filter_results
        _ARRAYS = [
            'filtered_state', 'filtered_state_cov',
            'forecasts_error',
            'standardized_forecasts_error', 'forecasts_error_cov',
            'kalman_gain',
        ]
        for attr_name in _ARRAYS:
            try:
                arr = getattr(fr, attr_name, None)
            except Exception:
                continue
            if isinstance(arr, np.ndarray) and arr.ndim >= 1 and arr.shape[-1] > _MAX_OBS:
                try:
                    slicing = [slice(None)] * (arr.ndim - 1) + [slice(-_MAX_OBS, None)]
                    setattr(fr, attr_name, arr[tuple(slicing)].copy())
                except Exception:
                    pass

    if hasattr(model_obj, 'smoother_results'):
        sr = model_obj.smoother_results
        for attr_name in ['smoothed_state', 'smoothed_state_cov', 'smoothed_state_autocov',
                           'scaled_smoothed_estimator', 'scaled_smoothed_estimator_cov',
                           'smoothing_error', 'smoothed_measurement_disturbance',
                           'smoothed_state_disturbance', 'smoothed_measurement_disturbance_cov',
                           'smoothed_state_disturbance_cov']:
            try:
                arr = getattr(sr, attr_name, None)
            except Exception:
                continue
            if isinstance(arr, np.ndarray) and arr.ndim >= 1 and arr.shape[-1] > _MAX_OBS:
                try:
                    slicing = [slice(None)] * (arr.ndim - 1) + [slice(-_MAX_OBS, None)]
                    setattr(sr, attr_name, arr[tuple(slicing)].copy())
                except Exception:
                    pass

    for attr_name in ('level', 'trend', 'seasonal'):
        try:
            arr = getattr(model_obj, attr_name, None)
        except Exception:
            continue
        if isinstance(arr, np.ndarray) and arr.ndim >= 1 and arr.shape[0] > _MAX_OBS:
            try:
                setattr(model_obj, attr_name, arr[-_MAX_OBS:].copy())
            except Exception:
                pass


def save_trained_model(model_obj, dataset_id, model_name, target_column, date_column,
                       forecast_horizon, feature_columns, training_samples, testing_samples,
                       dataset_name, trained_model_extra=None):
    model_dir = _get_model_dir(dataset_id)
    os.makedirs(model_dir, exist_ok=True)

    framework = _detect_framework(model_obj)
    versions = _get_framework_versions()
    timestamp = datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')

    metadata = {
        'dataset_name': dataset_name,
        'forecast_model': model_name,
        'target_column': target_column,
        'date_column': date_column,
        'forecast_horizon': forecast_horizon,
        'training_samples': training_samples,
        'testing_samples': testing_samples,
        'feature_columns': feature_columns,
        'feature_count': len(feature_columns),
        'training_timestamp': timestamp,
        'framework': framework,
        'framework_versions': versions,
        'model_version': '1.0.0',
    }

    if framework == 'tensorflow':
        keras_path = os.path.join(model_dir, 'model.keras')
        model_obj.save(keras_path)
    elif framework == 'xgboost':
        native_path = os.path.join(model_dir, 'model.json')
        model_obj.save_model(native_path)
        pkl_path = os.path.join(model_dir, 'model.pkl')
        joblib.dump(model_obj, pkl_path)
    elif framework == 'lightgbm':
        native_path = os.path.join(model_dir, 'model.txt')
        model_obj.save_model(native_path)
        pkl_path = os.path.join(model_dir, 'model.pkl')
        joblib.dump(model_obj, pkl_path)
    elif framework == 'catboost':
        native_path = os.path.join(model_dir, 'model.cbm')
        model_obj.save_model(native_path)
        pkl_path = os.path.join(model_dir, 'model.pkl')
        try:
            joblib.dump(model_obj, pkl_path)
        except Exception:
            pass
    elif framework == 'prophet':
        from prophet.serialize import model_to_json
        prophet_path = os.path.join(model_dir, 'model.json')
        with open(prophet_path, 'w') as f:
            f.write(model_to_json(model_obj))
        pkl_path = os.path.join(model_dir, 'model.pkl')
        try:
            joblib.dump(model_obj, pkl_path)
        except Exception:
            pass
    else:
        pkl_path = os.path.join(model_dir, 'model.pkl')
        if framework == 'statsmodels':
            _trim_statsmodels_model(model_obj)
        joblib.dump(model_obj, pkl_path)

    preprocessor = {
        'date_column': date_column,
        'target_column': target_column,
        'feature_columns': feature_columns,
        'forecast_horizon': forecast_horizon,
        'is_time_series': len(feature_columns) == 0,
    }
    if trained_model_extra:
        preprocessor['numeric_features'] = trained_model_extra.get('numeric_features', [])
        preprocessor['date_features_created'] = trained_model_extra.get('date_features_created', False)
    joblib.dump(preprocessor, os.path.join(model_dir, 'preprocessor.pkl'))

    with open(os.path.join(model_dir, 'feature_columns.json'), 'w', encoding='utf-8') as f:
        json.dump(feature_columns, f, indent=2)

    with open(os.path.join(model_dir, 'metadata.json'), 'w', encoding='utf-8') as f:
        json.dump(metadata, f, indent=2)

    readme = _generate_readme(metadata)
    with open(os.path.join(model_dir, 'README.txt'), 'w', encoding='utf-8') as f:
        f.write(readme)

    requirements = _generate_requirements(framework)
    with open(os.path.join(model_dir, 'requirements.txt'), 'w', encoding='utf-8') as f:
        f.write(requirements)

    return model_dir


def validate_model_package(dataset_id):
    model_dir = _get_model_dir(dataset_id)
    if not os.path.exists(model_dir):
        return False, 'No trained model found. Run forecasting first.'

    required_files = ['model.pkl', 'preprocessor.pkl', 'feature_columns.json',
                      'metadata.json', 'README.txt', 'requirements.txt']

    framework = 'unknown'
    meta_path = os.path.join(model_dir, 'metadata.json')
    if os.path.exists(meta_path):
        try:
            with open(meta_path, 'r') as f:
                meta = json.load(f)
            framework = meta.get('framework', 'unknown')
        except Exception:
            pass

    if framework == 'tensorflow':
        required_files.remove('model.pkl')
        required_files.append('model.keras')
    elif framework == 'prophet':
        required_files.remove('model.pkl')
        required_files.append('model.json')

    for fname in required_files:
        fpath = os.path.join(model_dir, fname)
        if not os.path.exists(fpath):
            return False, f'Required file missing: {fname}'
        try:
            with open(fpath, 'rb') as f:
                f.read(1)
        except Exception as e:
            return False, f'File unreadable: {fname} ({str(e)})'

    try:
        with open(meta_path, 'r') as f:
            meta = json.load(f)
        required_meta = ['forecast_model', 'training_timestamp', 'target_column']
        for field in required_meta:
            if field not in meta:
                return False, f'Metadata field missing: {field}'
    except Exception as e:
        return False, f'Metadata file corrupt: {str(e)}'

    return True, None


def get_trained_model_info(dataset_id):
    model_dir = _get_model_dir(dataset_id)
    if not os.path.exists(model_dir):
        return None, None, 'No trained model found.'

    meta_path = os.path.join(model_dir, 'metadata.json')
    if not os.path.exists(meta_path):
        return None, None, 'Metadata file not found.'

    with open(meta_path, 'r') as f:
        meta = json.load(f)

    framework = meta.get('framework', 'unknown')
    model_name = meta.get('forecast_model', 'Model')

    if framework == 'tensorflow':
        model_file = 'model.keras'
        ext = '.keras'
    else:
        model_file = 'model.pkl'
        ext = '.pkl'

    model_path = os.path.join(model_dir, model_file)
    if not os.path.exists(model_path):
        return None, None, f'Model file not found: {model_file}'

    download_name = f'{model_name}_Model{ext}'
    return model_path, download_name, None


def create_model_zip(dataset_id, dataset_name=None):
    valid, err = validate_model_package(dataset_id)
    if not valid:
        return None, err

    model_dir = _get_model_dir(dataset_id)

    meta_path = os.path.join(model_dir, 'metadata.json')
    with open(meta_path, 'r') as f:
        meta = json.load(f)
    model_name = meta.get('forecast_model', 'Model')
    base = dataset_name or f'model_{dataset_id}'
    zip_name = f'{model_name}_Model.zip'

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(model_dir):
            for fname in files:
                fpath = os.path.join(root, fname)
                arcname = os.path.relpath(fpath, model_dir)
                zf.write(fpath, arcname)

    buf.seek(0)
    return buf, None
